### ISSUE TITLE
The NPE in the SimpleDiskCache.writeMetadata(...)

### ISSUE THREAD

**Issue by makovkastar** [anupcowkur/Reservoir#11]
I don't know if I did something wrong with the library, but I've got a new crash report from a user. Could you check it?

The stack trace:
```
java.lang.NullPointerException
       at com.anupcowkur.reservoir.SimpleDiskCache.writeMetadata(SimpleDiskCache.java:108)
       at com.anupcowkur.reservoir.SimpleDiskCache.openStream(SimpleDiskCache.java:73)
       at com.anupcowkur.reservoir.SimpleDiskCache.put(SimpleDiskCache.java:95)
       at com.anupcowkur.reservoir.SimpleDiskCache.put(SimpleDiskCache.java:83)
       at com.anupcowkur.reservoir.Reservoir.put(Reservoir.java:47)
      ...

**Comment by anupcowkur** [comment]
closing for now. Will re-open if I can get a reproducible sample.
