### ISSUE TITLE
GSON Error

### ISSUE THREAD

**Issue by JeffreyCA** [anupcowkur/Reservoir#40]
I get this GSON error when using `Reservoir.get`. 

```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $
08-16 22:26:38.087 18657-18944/ca.jeffrey.apodgallery W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
08-16 22:26:38.087 18657-18944/ca.jeffrey.apodgallery W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:887)
08-16 22:26:38.087 18657-18944/ca.jeffrey.apodgallery W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:852)
08-16 22:26:38.087 18657-18944/ca.jeffrey.apodgallery W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:801)
08-16 22:26:38.087 18657-18944/ca.jeffrey.apodgallery W/System.err:     at com.google.gson.Gson.fromJson(Gson.java:773)
08-16 22:26:38.087 18657-18944/ca.jeffrey.apodgallery W/System.err:     at com.anupcowkur.reservoir.Reservoir.get(Reservoir.java:176)
```

**Comment by JeffreyCA** [comment]
I solved this by declaring a new `TestClass` object to store the value of `Reservoir.get`.
